### PR TITLE
update stimulus to 1.1.1 not minified

### PR DESCRIPTION
**Pull request by localhostdotdev**
minification is done my the preprocessor (e.g. uglifier) if needed (e.g. prod)

### CODE REVIEW

**Comment by bricesanchez** [comment]
Hi @localhostdotdev,

I agree but what is the source of stimulus you use ? 

There are diff with this source: https://unpkg.com/stimulus@1.1.1/dist/stimulus.umd.js

**Comment by localhostdotdev** [comment]
@bricesanchez I cloned the stimulus repo and did a manual build, didn't know it was on unpkg (I tried cdnjs). will update to that code

**Comment by bricesanchez** [comment]
Thanks @localhostdotdev !

**Comment by bricesanchez** [comment]
It's released on rubygems : https://rubygems.org/gems/stimulusjs-rails

**Comment by localhostdotdev** [comment]
wow!!! my Gemfile says thank you :)

**Pull request merged**
